version: '3.8'

services:
  marketplace:
    environment:
      - NODE_ENV=development
    volumes:
      - ./src:/app/src
      - ./dist:/app/dist
      - /app/node_modules
    ports:
      - "3002:3002"

  mcp-bridge:
    environment:
      - NODE_ENV=development
    volumes:
      - ./modules/mcp-bridge:/app
      - /app/node_modules

  resource-controller:
    environment:
      - NODE_ENV=development
    volumes:
      - ./modules/resource-controller:/app
      - /app/node_modules
