version: '3.8'

services:

  mcp-bridge:
    build:
      context: ./modules/mcp-bridge
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production

  resource-controller:
    build:
      context: ./modules/resource-controller
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production

  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    ports:
      - "8080:80"
      - "8443:443"
    depends_on:
      - mcp-bridge
      - resource-controller
