version: '3.8'

services:
  marketplace:
    build:
      context: ./docker/marketplace
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ../pwa-marketplace/src:/app/src
      - ../pwa-marketplace/dist:/app/dist
    environment:
      - NODE_ENV=production

  mcp-bridge:
    build:
      context: ./modules/mcp-bridge
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production

  resource-controller:
    build:
      context: ./modules/resource-controller
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production

  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - marketplace
      - mcp-bridge
      - resource-controller
