version: '3.8'

services:

  mcp-bridge:
    environment:
      - NODE_ENV=development
    volumes:
      - ./modules/mcp-bridge:/app
      - /app/node_modules

  resource-controller:
    environment:
      - NODE_ENV=development
    volumes:
      - ./modules/resource-controller:/app
      - /app/node_modules
