FROM node:18-slim

WORKDIR /app

# Copy package files
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy source code
COPY src ./src

# Expose resource controller ports
EXPOSE 8082
EXPOSE 8083

# Start the resource controller server
CMD ["npm", "start"]
