version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app/frontend
    environment:
      - NODE_ENV=production

  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app/backend
    environment:
      - NODE_ENV=production
    depends_on:
      - nginx

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./storage:/app/storage
    depends_on:
      - frontend
      - backend
